import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
  },
  backButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '600', color: '#333' },
  scrollContent: { paddingHorizontal: 20 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 20, marginBottom: 10 },
  sectionTitle: { fontSize: 13, fontWeight: '600', color: '#6A46EB' },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  cardInput: { paddingHorizontal: 16, paddingVertical: 14, fontSize: 15, color: '#333' },
  divider: { height: 1, backgroundColor: '#F0F0F0', marginHorizontal: 16 },
  statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statusOption: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF',
    borderRadius: 10,
    padding: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  radioOuter: {
    width: 20, height: 20, borderRadius: 10,
    borderWidth: 2, borderColor: '#C3C5CB',
    alignItems: 'center', justifyContent: 'center',
  },
  radioSelected: { borderColor: '#6A46EB' },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#6A46EB' },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, gap: 5 },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusText: { fontSize: 12, fontWeight: '600' },
  serviceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  serviceLeft: { flex: 1, marginRight: 8 },
  serviceTitle: { fontSize: 14, fontWeight: '700', color: '#333' },
  serviceDesc: { fontSize: 12, color: '#999', marginTop: 2 },
  serviceRight: { alignItems: 'flex-end' },
  serviceValue: { fontSize: 14, fontWeight: '700', color: '#333' },
  serviceQty: { fontSize: 12, color: '#999' },
  addServiceBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 14 },
  addServiceText: { color: '#6A46EB', fontSize: 14, fontWeight: '600' },
  investRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12 },
  investLabel: { fontSize: 14, color: '#666' },
  investMeta: { fontSize: 11, color: '#999' },
  investValue: { fontSize: 14, fontWeight: '600', color: '#333' },
  discountBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F5F5F5', borderRadius: 8, paddingHorizontal: 10, marginHorizontal: 8 },
  discountInput: { fontSize: 14, color: '#333', minWidth: 32, textAlign: 'center', paddingVertical: 6 },
  discountPct: { fontSize: 14, color: '#666' },
  discountValue: { fontSize: 14, fontWeight: '600', color: '#D84D4D' },
  totalLabel: { fontSize: 15, fontWeight: '700', color: '#333' },
  totalValue: { fontSize: 18, fontWeight: '700', color: '#333' },
  strikethrough: { fontSize: 12, color: '#999', textDecorationLine: 'line-through' },
  footer: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
    paddingBottom: Platform.OS === 'ios' ? 36 : 20,
    backgroundColor: '#F5F5F5',
    borderTopWidth: 1,
    borderTopColor: '#E6E5E5',
  },
  cancelBtn: { flex: 1, height: 44, borderRadius: 22, borderWidth: 1, borderColor: '#C3C5CB', alignItems: 'center', justifyContent: 'center' },
  cancelText: { fontSize: 15, color: '#676767', fontWeight: '600' },
  saveBtn: { flex: 2, height: 44, borderRadius: 22, backgroundColor: '#6A46EB', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  saveText: { color: '#FFF', fontSize: 15, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#FFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 36 },
  modalHandleBar: { width: 40, height: 4, backgroundColor: '#E0E0E0', borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#333' },
  modalCloseBtn: { width: 32, height: 32, backgroundColor: '#F5F5F5', borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  modalInput: { borderWidth: 1, borderColor: '#E6E5E5', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: '#333', marginBottom: 12, backgroundColor: '#FAFAFA' },
  modalTextArea: { minHeight: 80 },
  modalValueRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  modalValueBox: { flex: 1, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E6E5E5', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: '#FAFAFA', gap: 6 },
  currencyLabel: { fontSize: 15, fontWeight: '600', color: '#333' },
  modalValueInput: { flex: 1, fontSize: 15, color: '#333' },
  qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  qtyBtn: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, borderColor: '#E6E5E5', alignItems: 'center', justifyContent: 'center', backgroundColor: '#F5F5F5' },
  qtyValue: { fontSize: 18, fontWeight: '600', color: '#333', minWidth: 32, textAlign: 'center' },
  modalFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  deleteBtn: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: '#FFD6D6', backgroundColor: '#FFF5F5', alignItems: 'center', justifyContent: 'center' },
});